version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0

jobs:
  test:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test

workflows:
  build-and-deploy:
    jobs:
      - test

      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"  
          requires:
            - test

      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
      #     # family: "${AWS_RESOURCE_NAME_PREFIX}-service"
      #     family: "${AWS_RESOURCE_NAME_PREFIX}"
      #     cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
      #     service-name: "${AWS_RESOURCE_NAME_PREFIX}-service"
      #     container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"     